
ALTER TABLE ARTICLE_CATEGORY ADD FOREIGN KEY 
fk_categoryid (idCATEGORY) 
REFERENCES ARTICLE (idARTICLE);

ALTER TABLE `paschal_socialpub`.`ARTICLE_CATEGORY` 
  ADD CONSTRAINT `fk_ARTICLE_CATEGORY_1`
  FOREIGN KEY (`idARTICLE` )
  REFERENCES `paschal_socialpub`.`ARTICLE` (`idARTICLE` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_ARTICLE_CATEGORY_1_idx` (`idARTICLE` ASC)

